---
roles:
  - name: buluma.bootstrap
  - name: buluma.epel
  - name: buluma.centos_base
  - name: buluma.ruby
  - name: buluma.mysql
  - name: buluma.postgresql
collections:
  - name: community.general
  - name: ansible.posix
