---
roles:
  - name: buluma.bootstrap
  # - name: buluma.postgresql
  - name: radamanth.mysql-ansible
    src: radamanth.mysql-ansible
    version: 1.0.4
collections:
  - name: community.general
  - name: ansible.posix
