---
roles:
  - name: buluma.bootstrap
  - name: buluma.epel
  - name: bngsudheer.centos_base
  - name: buluma.ruby
  - name: buluma.mysql
  - name: geerlingguy.postgresql
collections:
  - name: community.general
  - name: ansible.posix
