---
- name: daemon reload
  systemd:
    daemon_reload: yes
    # name: "{{app.value.redmine.user.user}}-redmine.service"
    name: "root-redmine.service"
  become: True

- name: restart redmine
  service:
    # name: "{{app.value.redmine.user.user}}-redmine.service"
    name: "root-redmine.service"
    state: restarted
  become: True
