- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.mysql
      mysql_databases:
        - name: redmine
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: redmine
          password: password
          priv: "redmine.*:ALL"
          update_password: on_create

    - role: buluma.redmine
